# Server Configuration
server:
  port: 8086

# Spring Application Configuration
spring:
  application:
    name: cart-service

  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5436/bakery_carts
    username: cart_user
    password: cart_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  docker:
    compose:
      file: docker-compose-carts-db.yml
      enabled: false

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
      cache-null-values: false

  # Jackson Configuration
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  data:

    # Redis Configuration
    redis:
      host: localhost
      timeout: 60000
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Feign Configuration
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Management & Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, caches
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true

# Cart Service Specific Configuration
cart:
  # Cart expiration settings
  expiration:
    guest-cart-hours: 24          # Guest carts expire after 24 hours
    user-cart-days: 30            # User carts expire after 30 days
    cleanup-interval-hours: 6     # Clean up expired carts every 6 hours

  # Cart limits
  limits:
    max-items-per-cart: 100       # Maximum items in a cart
    max-quantity-per-item: 50     # Maximum quantity for single item
    max-cart-value: 2000.00       # Maximum cart value

  # Cache settings
  cache:
    cart-ttl-minutes: 30          # Cart cache TTL
    product-info-ttl-minutes: 10  # Product info cache TTL

  # Validation settings
  validation:
    check-stock-on-add: true      # Check stock when adding items
    check-price-on-view: true     # Check prices when viewing cart
    auto-remove-unavailable: true # Remove unavailable items

# External Service URLs
external-services:
  product-service:
    base-url: http://localhost:8083
  order-service:
    base-url: http://localhost:8084

# Logging Configuration
logging:
  level:
    com.shah_s.bakery_cart_service: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
    feign: DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/cart-service.log
    max-size: 10MB
    max-history: 30
